### PR TITLE
Standard

### PR DESCRIPTION
**Pull request by kizza**
Just a few changes here and there (for standardjs)

### CODE REVIEW

**Comment by slwen** [comment]
This looks good, though one thing I came across is that in the `gulpfile` there is still a reference to the lint task, that should be cleaned up. Currently this causes some breaks when building assets.

Not sure if it's in your current scope but it might also be nice to still see lint warnings alongside the dev output. Useful for those that don't have standard configured for their editors.

**Comment by slwen** [comment]
Also noticed when running locally quite a few console errors, not sure if these are new though? Maybe out of scope for what you are tackling right now.

screen shot 2016-10-21 at 2 58 55 pm

**Comment by kizza** [comment]
Cheers @slwen - I literally just noticed the gulp lint stuff hanging around myself when trying to run `npm run dev`, i'll clean that up in this pr.  Console warnings... I believe they would have been introduced with the upgrade to react 15 which was merged before this branch... leaning towards putting them into another pr. Thoughts?

**Comment by kizza** [comment]
Ok, @slwen I made the "add standard" implement [gulp-standard](https://www.npmjs.com/package/gulp-standard) in https://github.com/everydayhero/hui/pull/408/commits/242ffd48ff6fb23d71c3005597640cd4ded480bd, then made the "remove eslint" commit not touch any of the gulp linting in https://github.com/everydayhero/hui/pull/408/commits/d119aa2c71aa1d90ef17d0f0b9b79e4097b58b62.

**Pull request merged**
