### PR TITLE
Fix checkbox error styling

### PR DESCRIPTION
**Pull request by Mbuckley0**

### CODE REVIEW

**Comment by Mbuckley0** [comment]
screen shot 2015-06-25 at 1 57 32 pm

**Comment by davidherse** [comment]
Can you make sure the font is the same as the other error messages and add some margin about it please?

**Comment by Mbuckley0** [comment]
screen shot 2015-06-25 at 2 39 15 pm

**Comment by davidherse** [comment]
Still needs more space between the text and the error box.

**Comment by Mbuckley0** [comment]
screen shot 2015-06-25 at 2 52 01 pm

**Pull request merged**
